name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [published]  # triggers publish job only on GitHub releases

jobs:
  test:
    name: Run Tests & Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv pip install -r pyproject.toml

      - name: Run tests with coverage
        run: pytest --cov=bria --cov-report=term-missing --maxfail=1 --disable-warnings -q

  publish:
    name: Build & Publish to PyPI
    runs-on: ubuntu-latest
    needs: test   # ensures tests pass before attempting to publish
    if: github.event_name == 'release'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: pip install uv

      - name: Build package
        # run: uv build
        run: echo "Build step is commented out for safety"

      - name: Publish to PyPI
        # run: uv publish --token ${{ secrets.PYPI_TOKEN }}
        run: echo "Publish step is commented out for safety"